services:
  - name: no-15
    type: web
    env: python
    plan: free
    buildCommand: |
       pip install playwright
       playwright install
       pip install --upgrade pip
  pip install -r requirements.txt
  playwright install --with-deps chromium
  apt-get update && apt-get install -y libnss3 libatk1.0-0 libxcomposite1 libxrandr2 libxdamage1 libgbm1 libasound2
    startCommand: python app.py
    envVars:
      - key: INSTA_USERNAME
        value: "your_username"
      - key: INSTA_PASSWORD
        value: "your_password"
      - key: PORT
        value: "10000"
