services:
  - name: no-20
    type: web
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      npx playwright install --with-deps chromium
    startCommand: python app.py
    envVars:
      - key: INSTA_USERNAME
        value: "your_username"
      - key: INSTA_PASSWORD
        value: "your_password"
      - key: PORT
        value: "10000"
